### PR TITLE
Add zh_TW translation.

### PR DESCRIPTION
**Pull request by s8321414**
Markdown file translated, about image, I may or may not do it :P

### CODE REVIEW

**Comment by gdpelican** [comment]
Brilliant, thank you, @s8321414 !

**Comment by s8321414** [comment]
I think use language variant will be good, like zh_TW or zh-TW for Chinese (Taiwan), and please enable this language! XD

**Comment by s8321414** [comment]
Hi, can anyone enable Chinese(Taiwan) translation as zh-TW or zh_TW?

**Comment by s8321414** [comment]
Or should I open another PR to do this? :P

**Comment by gdpelican** [comment]
Thanks Jeff, we will get this done next week. 

https://github.com/loomio/loomio/issues/3060

:)

**Pull request merged**
